version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-template"
s3_bucket = "m-tracer-dev-lambda"
s3_prefix = "lambda-template"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
