version: "3"
services:
  lambda:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    environment:
      - http_proxy
      - https_proxy
      - no_proxy
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/root/.gitconfig      
    working_dir: /workspace
    command: sleep infinity
